influx:
  database: wbmpoll
  enabled: false
  host: localhost
  port: 8086
  retention_period: 30d
logging:
  level: INFO
scraping:
  enabled: false
  max_pages: 20
  parser: html.parser
  proxy: null
  shelve_file: listings.data
  sites:
  - degewo
  - wbm
  - howoge
  - stadtundland
  - gewobag
  - gesobau
  - inberlinwohnen
  timeout: 10
  wgproxy_endpoint: null
  write_sample: true
telegram:
  enabled: true
  timeout: 10
