logging:
  level: DEBUG
monitoring:
  enabled: false
scraping:
  enabled: false
  parser: html.parser
  shelve_file: listings.data
  sites:
  - inberlinwohnen
  - wbm
  - degewo
  timeout: 10
  write_sample: false
telegram:
  enabled: false
  timeout: 10
