logging:
  level: INFO
influx:
  enabled: true
  host: localhost
  port: 8086
  database: wohnbot
  retention_period: 1h
scraping:
  enabled: false
  parser: html.parser
  shelve_file: listings.data
  sites:
  - inberlinwohnen
  - wbm
  - degewo
  - gesobau
  - gewobag
  - howoge
  - stadtundland
  timeout: 10
  write_sample: false  
  max_pages: 20
telegram:
  enabled: false
  timeout: 10
